name: instagram_repository

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_storage: ^7.0.0
  cloud_firestore: ^0.16.0+1
  rxdart: ^0.24.0
  equatable: ^1.2.5
  firebase_core: ^0.7.0
  authentication_repository:
    path: ../authentication_repository
  http: ^0.12.2
  flutter_webview_plugin: ^0.3.11

